#!/bin/bash

# test if package is installed. if not installed dpkg will return 0,
# if installed it will return 0, if not return 1

dpkg -l samba > /dev/null 2>&1
INSTALLED=$?

if [ $INSTALLED != 0 ]
    then
    sudo apt-get update && sudo apt -y install samba > /dev/null 2>&1

    SUCCESS=$?
    if [ $SUCCESS !=0 ]
        then
        echo "SAMBA was not installed!"
        exit 1
    fi
fi

